version: '3.8'

services:
  django:
    build: .
    # container_name: django
    
    volumes:
      - .:/python_task
    ports:
      - 8000:8000
    image: app:python_task
    container_name: python_task
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - pgdb
  pgdb:
    image: postgres:latest
    container_name: pgdb
    environment:
      - POSTRES_DB=postgres
      - POSTRES_USER=postgres
      - POSTRES_PASSWORD=postgres
