# Generated by Django 4.0.6 on 2022-08-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_employees_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Hot drinks', 'HOT DRINKS'), ('Cold drinks', 'COLD DRINKS'), ('Salads', 'SALADS')], max_length=25)),
                ('dish', models.CharField(blank=True, max_length=25)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='employees',
            field=models.ManyToManyField(to='restaurant.employee'),
        ),
    ]
