# Generated by Django 4.0.6 on 2022-08-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_restaurant_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, choices=[('HOT DRINKS', 'Hot drinks'), ('COLD DRINKS', 'Cold drinks'), ('SALADS', 'Salads')], max_length=25),
        ),
    ]
