# Generated by Django 4.0.6 on 2022-08-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_menus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('HOT DRINKS', 'Hot drinks'), ('COLD DRINKS', 'Cold drinks'), ('SALADS', 'Salads')], max_length=25)),
                ('component', models.CharField(blank=True, max_length=25)),
                ('price', models.FloatField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='category',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AddField(
            model_name='menu',
            name='components',
            field=models.ManyToManyField(to='restaurant.component'),
        ),
    ]
