# Generated by Django 4.0.6 on 2022-08-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_component_remove_menu_category_remove_menu_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
